Fix display bug
beattosetto/beattosetto pull request #96
Opened 2021-10-31 16:04 UTC by pontakornth

Currently, I fix the header and no beatmap one.  I will update my PR eventually.

<img width="1439" alt="Screen Shot 2564-10-31 at 23 03 28" src="https://user-images.githubusercontent.com/37771900/139592215-98ab4437-a643-478a-9528-697bda09ade8.png">
<img width="352" alt="Screen Shot 2564-10-31 at 23 03 40" src="https://user-images.githubusercontent.com/37771900/139592224-d9a79a5c-1d0c-44dc-921b-48b66b5d196d.png">

2021-11-01 18:19 UTC, HelloYeew requested changes
![image](https://user-images.githubusercontent.com/68165621/139720688-02f84d85-d504-461a-8c25-6be5af6a3c02.png)

![image](https://user-images.githubusercontent.com/68165621/139720912-72a7b42a-58f8-4397-98ee-db24b5c2061a.png)

A long word still have a bug. But if write it as a sentence the bug is disappear. Good job!

2021-11-02 02:34 UTC, pontakornth commented
> ![image](https://user-images.githubusercontent.com/68165621/139720688-02f84d85-d504-461a-8c25-6be5af6a3c02.png)
> 
> ![image](https://user-images.githubusercontent.com/68165621/139720912-72a7b42a-58f8-4397-98ee-db24b5c2061a.png)
> 
> A long word still have a bug. But if write it as a sentence the bug is disappear. Good job!


Fixed now.

<img width="382" alt="Screen Shot 2564-11-02 at 09 33 00" src="https://user-images.githubusercontent.com/37771900/139777428-b0d50b7f-6cc6-4a27-9c4a-9f9a548a26bc.png">

Note: All fixes here do not support Arabic language or language that write from right to left. It's CSS limitation right now. As long as no people use Arabic language, it is fine.

2021-11-02 03:38 UTC, HelloYeew approved these changes
It's fixed!

2021-11-02 08:44 UTC, some-random-idiot approved these changes

2021-11-02 08:45 UTC, Siraphop4Nene approved these changes

2021-11-02 08:48 UTC, SainTurDaY27 approved these changes

2021-11-02 09:28 UTC, merged